### ISSUE TITLE
Form validation glitch

### ISSUE THREAD

**Issue by Unisay** [thomashoneyman/purescript-halogen-formless#11]
## Environment

https://thomashoneyman.github.io/purescript-halogen-formless/#polyform

## Current behavior

Email validation is inconsistent: result changes drastically when editing name field.

![validation glitch](https://user-images.githubusercontent.com/1009751/43383566-b1ebd934-93db-11e8-8361-e56b3819a725.gif)

## Expected behavior
Email field validation doesn't depend on "Name"

**Comment by thomashoneyman** [comment]
Hi Yuriy!

This is a known issue, but perhaps not for the same reason you've mentioned here. The email field's validation does not depend on any other fields, but its validation is being run when any other field is modified. Since its validation is non-deterministic -- it's simply to flip a coin to see if the email is being used or not -- you're seeing the result of validation potentially change every time any field in the form is modified.

This issue happens because validation is run against the entire form when the `Validate` query is triggered in Formless. A validator in Formless has the type `form InputField -> m (Form InputField)`. At this point, there's not a way to specify that only a single field should be validated. Instead, all fields with `touched: true` are validated. In a pure validator this isn't an issue -- same input, same output -- but in a monadic one like `validateEmailIsUsed` you're seeing the problem.

See this post for more details on why this is:
https://purescript-users.ml/t/call-for-feedback-formless-a-new-form-library-for-halogen/308/4?u=thomashoneyman

I have a few ideas that would either a) not re-compute validation on any field where the input is unchanged since the last run; or b) allow the ability to run validation or modification on a single field only. 

However, these are still in pretty rough idea stage at the moment. For the moment, be careful when using effectful validators in Formless.

**Comment by safareli** [comment]
Maybe use some deterministic simulation for email used? like number of length or number of some chars in it

**Comment by thomashoneyman** [comment]
@safareli Yes, I could go ahead and update the example so that the email is deterministic, and that would solve the flickering issue that @Unisay noticed. I'll do that for the time being in the examples. However the underlying problem -- that the check is going to be run, and potentially expensively, every time any field triggers a `Validate` query on the component -- can only be solved by a different approach to this validation altogether.

I do have something in the works based on variants -- and that _ought_ to solve this and allow validation to run on a single field.

**Comment by thomashoneyman** [comment]
I've updated the example to be deterministic for the time being.

**Comment by safareli** [comment]
> I've updated the example to be deterministic for the time being.

Nice!

At first the flicker gave me a feeling that the lib was buggy, and before I opened the example, I had already read your thread and was aware of the limitation.

**Comment by Unisay** [comment]
Thanks,
I understood why that flickering happened, 
and also I agree with the decision to simplify validation for the sake of a better demo experience.

**Comment by thomashoneyman** [comment]
@Unisay @safareli I've introduced #14 which solves this issue by making per-field validation possible. Once merged, I'll close this issue.

**Comment by thomashoneyman** [comment]
Fixed in #14
