### ISSUE TITLE
How to optionally combine validators

### ISSUE THREAD

**Issue by dariooddenino** [thomashoneyman/purescript-halogen-formless#30]
Hi! Sorry for spamming your issues :D

I'll explain this use case, hoping that there's a better solution than the one I'm using.

I have an optional phone field and I already have a `validPhone` validator that runs a regex to check that the number is in the correct format.
Since the field is optional, I only want to run it when the field is not empty.

Out of stubborness I didn't want to write a `validPhone_`, so what I did is:

````
emptyStr = hoistFnE_ $ \str -> 
  if null str 
  then Right str 
  else Left Missing
```

and then in the validators:
```
phone: emptyStr <|> validPhone
```

This works, but I don't like this solution at all as I'm using a fake error that's never going to be used in `emptyStr`, and there's a chance that the validator is used improperly somewhere else.

Is there a better way to achieve this?
Thanks!

**Comment by thomashoneyman** [comment]
Here's one way you could solve the problem. First, let's say this is your underlying validation and sample form type:

```purescript
data Error = Error

-- Only represents validated phones
newtype ValidPhone = ValidPhone String

newtype MyForm r f = MyForm (r (phone :: f Error String (Maybe ValidPhone)))

-- This would be your regex
validPhone :: ∀ form m. Monad m => F.Validation form m Error String ValidPhone
validPhone = F.hoistFnE_ \str ->
  if String.length str == 10
    then Right $ ValidPhone str
    else Left Error
```

Next, what we want to do is take our validation function that outputs a `ValidPhone` and modify it so that it outputs a `Maybe ValidPhone` to represent being optional. If the value is `Nothing` then the input string was empty; otherwise, the input was non-empty and the result is `Just (ValidPhone ...)`.

We can write a helper function that will take any validation function and make it optional, where empty strings always validate to a `Nothing` value successfully:

```purescript
acceptEmpty
  :: ∀ form m o
   . Monad m
  => F.Validation form m Error String o
  -> F.Validation form m Error String (Maybe o)
acceptEmpty validator = F.Validation \form str ->
  if null str
    then pure (Right Nothing)
    else do
      res <- F.runValidation validator form str
      pure (map Just res)
```

Then, to turn our `validPhone` validator into an optional one, we can use the helper:

```purescript
maybeValidPhone :: ∀ form m. Monad m => F.Validation form m Error String (Maybe ValidPhone)
maybeValidPhone = acceptEmpty validPhone
```

**Comment by dariooddenino** [comment]
Thanks, this is much better. I was missing how to combine `Validation`s together
