### ISSUE TITLE
Cannot create forms with file uploads: `File` does not have an `Eq` or `Initial` type class instance

### ISSUE THREAD

**Issue by JordanMartinez** [thomashoneyman/purescript-halogen-formless#61]
## Environment

* `purescript-halogen` **v5.0.0-rc.7**
* `purescript-halogen-formless` **v1.0.0-rc.1**

## Current Behavior

I'm trying to use this library to upload a file in a form. Since `<input type="file">` doesn't have a `onValueInput` or something like that, I'm using a separate action to get the resulting file via `onFileUpload`:
```purescript
-- inside the render function
HH.input
        [ HP.type_ InputFile
        , HP.accept -- accept args
        , HP.value "Select File..."
        , HE.onFileUpload (Just <<< F.injAction <<< HandleFileUpload)
        ]
```
I can get the file fine...
```purescript
  handleAction
    :: Action
    -> F.HalogenM Form AddedState Action ChildSlots Message m Unit
  handleAction = case _ of
    HandleFileUpload fileArray -> do
      case fileArray of
        [file] -> do
          evalA (F.setValidate _artifactFile file)
        _ -> pure unit
```
... but `F.handleAction` requires the field whose value I'm setting to have an `Eq` instance. Unfortunately, `File` does not have such an instance. I'm not sure whether it can have an Eq instance, but I at least implemented the following to get around that issue:
```purescript
newtype FileEq = FileEq File
derive instance newtypeFileEq :: Newtype FileEq _
instance eqFileEq :: Eq FileEq where
  eq (FileEq left) (FileEq right) =
    (File.name left == File.name right) &&
    ((ceil $ File.size left) == (ceil $ File.size right))

  handleAction
    :: Action
    -> F.HalogenM Form AddedState Action ChildSlots Message m Unit
  handleAction = case _ of
    HandleFileUpload fileArray -> do
      case fileArray of
        [file] -> do
          evalA (F.setValidate _artifactFile $ FileEq file)
        _ -> pure unit
```
The next issue I run into is that `File` does not have a type class instance for `Initial`.

## Workaround...?

I think this would work:
- add a row in the Additional State rows for storing the file as a `Maybe File`
- Update that part of the state record when user selects a new file and also set the form's validity to `Valid`
- when user clicks the submit button, the file is included in the message raised to the parent.

**Comment by thomashoneyman** [comment]
Thanks for opening this issue -- I haven't yet done anything with file uploads in Formless myself. It's late here, so I want to start by explaining why you're seeing what you're seeing and I'll have to think about solutions tomorrow.

### Inputs requiring `Eq`

The first problem you have is that you're using an input type `File` and you get a compiler error because it doesn't have an `Eq` instance. I require an `Eq` instance for input types because I need a way to tell if a form field value is dirty -- that is, that it has been changed from its original value when the form was instantiated.

https://github.com/thomashoneyman/purescript-halogen-formless/blob/d7151f89d870b0e5647ac3ce76ec13d184e047b5/src/Formless/Types/Form.purs#L12-L16

There may be a few solutions to this one:

- I'm not entirely sure it's necessary to maintain in state whether a form is dirty or not. At the time I implemented it this information seemed useful, but I've never used it in practice. I ordinarily only care whether or not a particular field has been touched. And I suspect it's enough to know whether the user has touched any field in order to know if the form is dirty. If a field has been touched then in the vast majority of cases the form will be dirty. So one quick and dirty solution is to simply drop this information and thus the `Eq` requirement.
- It may be enough to use `unsafeRefEq` to check the form, if it's the case that editing the form will create a new object. Then we can just check whether the reference has changed and not bother with the much more expensive `Eq` check being performed right now and still have an accurate result. I'd need to test this.

### Inputs requiring `Initial`

The second problem you described is that your custom `FileEq` type (and the `File` type underneath) don't have instances for `Initial` and so Formless rejects it. This shouldn't be a problem -- you should only require an instance for `Initial` if:

- You are not providing an input, and Formless is constructing it for you (you set `initialInputs` to `Nothing`)
- You are using the Formless actions `reset` or `resetAll`, which set a field to its `initial` value

Unfortunately, when I looked at the component constraints I see this:

https://github.com/thomashoneyman/purescript-halogen-formless/blob/d7151f89d870b0e5647ac3ce76ec13d184e047b5/src/Formless/Component.purs#L100

which requires all input types to be an instance of `Initial`. This is not my intention -- you should be able to use Formless without worrying about this type class, if you want. I'm not yet sure how to update things so that inputs are not required to have this instance. It's certainly incorrect, though.

### Other solutions

I recognize that the issues you're facing here really ought not be problems in this library. It may be possible to do another workaround, and you mentioned doing so using additional state. But you shouldn't _have_ to do that.

That said, you may need to use that method for the time being until there's a proper solution to your underlying issues.

**Comment by ahnwarez** [comment]
@JordanMartinez 
I have the same exact issue and couldn't figure out how to solve until @thomashoneyman replied to my question on discource and shared a link to this issue here.

I've used your workaround in my code but not sure what to do with `evalA`? I would really appreciate if you share the implementation of `evalA`. 

```
handleAction
    :: Action
    -> F.HalogenM Form AddedState Action ChildSlots Message m Unit
  handleAction = case _ of
    HandleFileUpload fileArray -> do
      case fileArray of
        [file] -> do
          evalA (F.setValidate _artifactFile $ FileEq file) -- <-- ?
        _ -> pure unit
```

**Comment by JordanMartinez** [comment]
If you needed to run the code for a query (i.e. Query A) when you were evaluating Query B, you would use `eval (QueryB arg1 ...)`. However, Formless has to handle things specifically, so you can't use the normal `eval`. `evalA` is the same concept, but you wrap Formless' eval function. I think it's `evalA arg1 arg2 arg3 = Formless.handleAction arg1 arg2 arg3`. I can't recall what it is, but you're basically running the `Formless.handleAction` function.

**Comment by JordanMartinez** [comment]
Here it is: https://github.com/thomashoneyman/purescript-halogen-formless/blob/d7151f89d870b0e5647ac3ce76ec13d184e047b5/src/Formless/Component.purs#L188

```purescript
handleAction arg1 arg2 arg3 = do ...

  where
    evalA handleAction' handleEvent action = F.handleAction handleAction' handleEvent action
```

**Comment by thomashoneyman** [comment]
Formless no longer requires the `Eq` or `Initial` instances on fields, so this is no longer an issue. You can see the [file upload example](https://github.com/thomashoneyman/purescript-halogen-formless/blob/main/example/Example/FileUpload.purs) as a demonstration of how to create forms with file uploads in Formless 3.
