### ISSUE TITLE
Multiple async form fields share one debouncer, causing interference

### ISSUE THREAD

**Issue by thomashoneyman** [thomashoneyman/purescript-halogen-formless#64]
## Environment

* `purescript-halogen` **v5**
* `purescript-halogen-formless` **v0.5.2**

As described by @skress in #48:

> When a debouncer is used for one field and then for another field the running validation for the first field might get killed in atomic in `Internal.Debounce`:

```
  atomic
    :: forall n
     . MonadAff n
    => HalogenM form st act ps msg n (form Record FormField)
    -> Maybe (HalogenM form st act ps msg n a)
    -> HalogenM form st act ps msg n Unit
  atomic process maybeLast = do
    state <- H.get
    let ref = (unwrap state.internal).validationRef
    mbRef <- readRef ref
    for_ mbRef H.kill
    H.liftEffect $ for_ ref $ Ref.write Nothing
    forkId <- H.fork do
      form <- process
      H.modify_ _ { form = form }
      H.liftEffect $ for_ ref $ Ref.write Nothing
      for_ maybeLast identity
    H.liftEffect $ for_ ref $ Ref.write (Just forkId)
```

> Not sure what the best approach for a fix would be. Obviously there could be a debouncer per form field or only the forked validation (in atomic) could be run per form field.

**Comment by srghma** [comment]
probably experiencing this issue in feature tests

1.

- when test suite is inputting username (first) and email (second) field very fast
- AND when username `F.asyncSetValidate` is big - e.g. `(Milliseconds 300.0)`
- I'm getting old state for the `username` field (it's `u` instead of `username1`)

https://github.com/srghma/purescript-halogen-nextjs/blob/5becaac1878c20a432bff2eab6ede78cd4094c9f/packages/feature-tests/FeatureTests/Tests/Register/SuccessSpec.purs#L70-L80

![2020-12-05-22:11:14-screenshot](https://user-images.githubusercontent.com/7573215/101262367-dbcfd000-3746-11eb-8d5d-66bdbd9b0d83.png)

2. but with short `asyncSetValidate` for username (e.g. 30.0) - this issue is not happening

3. OR inputting username second time - fixes issue too

**Comment by thomashoneyman** [comment]
Thanks for the report, @srghma. I don't have time to dig into this at the moment, but I will certainly accept a PR which helps address the issue. The next version of this library is based on [halogen-hooks](https://github.com/thomashoneyman/purescript-halogen-hooks) and allows you to include whatever effects you want on a per-input basis (including debouncers) and won't suffer from this issue.

**Comment by srghma** [comment]
Thnx, why hooks, is ordinary halogen not good enough?)

**Comment by thomashoneyman** [comment]
Formless 3 doesn't include debouncing anymore because validators can now be run in your component's `HalogenM` and you can implement debouncing yourself however you'd like. For this reason, this issue no longer affects the library. Thanks!
