### ISSUE TITLE
sendQuery documentation outdated and I need an example

### ISSUE THREAD

**Issue by pmiddend** [thomashoneyman/purescript-halogen-formless#78]
The documentation for `sendQuery` is confusing:

    First, you can use H.query as usual within the handleExtraQuery function you provide to Formless as input. 

Is this up-to-date? I find no function `handleExtraQuery` in formless. I'm also not sure about `H.query`.

Also, it would be awesome to have an example of how to use the feature. What I'm trying to do is send the formless component a query so some input fields are then reset (I don't want to do this in the submit button's `onClick` handler since I want to make a HTTP request first and check the result).

**Comment by thomashoneyman** [comment]
That documentation does look out of date. To clarify, `sendQuery` is meant for when you have a formless component that has a child component that you want to query; you're sending the query _through_ the formless component.

There is an example of `sendQuery` used in the "real world" example. In the below code, we're sending a query through the "options form" to a dropdown component located in that form in order to manually reset it:

https://github.com/thomashoneyman/purescript-halogen-formless/blob/2e94bff0d99f48dae004b4fac943abb0ba62b5b2/example/real-world/GroupForm.purs#L186

However, if you just want to send a query to the formless component you've written and have _that_ component reset a few fields, then you don't want `sendQuery`. Instead, you want to write a query for your formless component and have the parent send a query through the ordinary `Halogen.query` mechanism.

There isn't an example of that, unfortunately, but it's the same idea as writing your own `Action`s for a formless component. First, you define your query type, similar to how the options form defines its action type:

https://github.com/thomashoneyman/purescript-halogen-formless/blob/3f6ffef29ac13587fea0ee2c608567c93fd867ae/example/real-world/OptionsForm.purs#L106-L107

Then, you write your query handler, similar to how the options form defines its `handleAction`:

https://github.com/thomashoneyman/purescript-halogen-formless/blob/3f6ffef29ac13587fea0ee2c608567c93fd867ae/example/real-world/OptionsForm.purs#L180-L183

Finally, you add the handler to your form spec with `handleQuery = handleQuery`:

https://github.com/thomashoneyman/purescript-halogen-formless/blob/3f6ffef29ac13587fea0ee2c608567c93fd867ae/example/real-world/OptionsForm.purs#L123-L127

With this all wired up, you can now send queries to your form component with the ordinary `Halogen.query` function.

**Comment by thomashoneyman** [comment]
@pmiddend Did this help you move forward, or are some things unclear?

**Comment by pmiddend** [comment]
Ah, sorry to let you hanging like this. This actually made it much clearer! However, while browsing through the real-world-halogen code, I discovered that my special use case can apparently be handled more easily using this code:

```
void $ H.query F._formless unit $ F.asQuery $ F.reset _dropId
```

Which is in my parent component `handleAction` method. I'm not really sure what it _does_, but it seems to work.

**Comment by thomashoneyman** [comment]
With that in mind I'm going to go ahead and close this. Glad things are working for you!
